"""ptite update

Revision ID: 38ce5460c9cc
Revises: 5529108555b2
Create Date: 2024-03-10 16:36:19.742671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38ce5460c9cc'
down_revision = '5529108555b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deal', schema=None) as batch_op:
        batch_op.drop_constraint('fk_game_tarot_game', type_='foreignkey')
        batch_op.create_foreign_key('fk_game_tarot_game', 'tarot_game', ['game_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deal', schema=None) as batch_op:
        batch_op.drop_constraint('fk_game_tarot_game', type_='foreignkey')
        batch_op.create_foreign_key('fk_game_tarot_game', 'tarot_game', ['game_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
