"""initialisation

Revision ID: 5a1319062366
Revises: 
Create Date: 2024-03-03 19:10:33.045394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a1319062366'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('gender', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_username'), ['username'], unique=True)

    op.create_table('tarot_game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_name', sa.String(length=64), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('last_accessed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tarot_game', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tarot_game_game_name'), ['game_name'], unique=True)

    op.create_table('deal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=True),
    sa.Column('called_id', sa.Integer(), nullable=True),
    sa.Column('nb_oudlers', sa.Integer(), nullable=False),
    sa.Column('nb_points', sa.Integer(), nullable=False),
    sa.Column('announcement', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['called_id'], ['player.id'], name='fk_called_player'),
    sa.ForeignKeyConstraint(['dealer_id'], ['player.id'], name='fk_dealer_player'),
    sa.ForeignKeyConstraint(['game_id'], ['tarot_game.id'], name='fk_game_tarot_game'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deal_called_id'), ['called_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deal_dealer_id'), ['dealer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deal_game_id'), ['game_id'], unique=False)

    op.create_table('players',
    sa.Column('tarotGame_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['tarotGame_id'], ['tarot_game.id'], ),
    sa.PrimaryKeyConstraint('tarotGame_id', 'player_id')
    )
    op.create_table('annonce',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('valeur', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deal.id'], name='fk_deal_annonce'),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], name='fk_player_annonce'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('annonce', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_annonce_deal_id'), ['deal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_annonce_player_id'), ['player_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annonce', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_annonce_player_id'))
        batch_op.drop_index(batch_op.f('ix_annonce_deal_id'))

    op.drop_table('annonce')
    op.drop_table('players')
    with op.batch_alter_table('deal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deal_game_id'))
        batch_op.drop_index(batch_op.f('ix_deal_dealer_id'))
        batch_op.drop_index(batch_op.f('ix_deal_called_id'))

    op.drop_table('deal')
    with op.batch_alter_table('tarot_game', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tarot_game_game_name'))

    op.drop_table('tarot_game')
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_username'))

    op.drop_table('player')
    # ### end Alembic commands ###
